# Generated by Django 4.2.13 on 2024-07-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
