# Generated by Django 4.2.13 on 2024-07-14 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0002_alter_app_user_is_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraUserDet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ABS.app_user')),
                ('Addhar', models.CharField(max_length=50)),
                ('Pan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ExtraUserDetails',
            },
        ),
    ]
