# Generated by Django 4.2.13 on 2024-07-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0003_extrauserdet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ABS.app_user')),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.AddField(
            model_name='extrauserdet',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
