# Generated by Django 4.2.13 on 2024-07-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0006_designation_staf_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('ambulance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ambulance_name', models.CharField(max_length=50)),
                ('ambulance_plate', models.CharField(max_length=15)),
                ('doctor', models.CharField(max_length=50)),
                ('cleaner', models.CharField(max_length=50)),
                ('driver', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Ambulance',
            },
        ),
    ]
