# Generated by Django 4.2.13 on 2024-07-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0008_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='address',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
