# Generated by Django 4.2.13 on 2024-07-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0009_book_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
