# Generated by Django 4.2.13 on 2024-10-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0010_ambulance_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted_rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_by', models.CharField(max_length=50)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('Addhar', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Accepted_rides',
            },
        ),
    ]
