# Generated by Django 4.2.13 on 2024-10-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0012_book_curr_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='curr_lat',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
