# Generated by Django 4.2.13 on 2024-10-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0013_book_curr_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='curr_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='curr_long',
            field=models.FloatField(),
        ),
    ]
