# Generated by Django 4.2.13 on 2024-10-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0014_alter_book_curr_lat_alter_book_curr_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted_rides',
            name='pikup_lat',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accepted_rides',
            name='pikup_long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
