# Generated by Django 4.2.13 on 2024-10-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0015_accepted_rides_pikup_lat_accepted_rides_pikup_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('ambulance_plate', models.CharField(max_length=15)),
                ('doctor', models.CharField(max_length=50)),
                ('cleaner', models.CharField(max_length=50)),
                ('driver', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('drop_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Finished_rides',
            },
        ),
    ]
