# Generated by Django 4.2.13 on 2024-10-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0016_finished_rides'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ambulance_plate',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
