# Generated by Django 4.2.13 on 2024-10-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0017_book_ambulance_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted_rides',
            name='accepted_booking_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
