# Generated by Django 4.2.13 on 2024-10-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0018_accepted_rides_accepted_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_rides',
            name='booking_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
