# Generated by Django 4.2.13 on 2024-10-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0019_finished_rides_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted_rides',
            name='ambulance_plate',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
