# Generated by Django 4.2.13 on 2024-10-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0020_accepted_rides_ambulance_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=50)),
                ('tool_price', models.IntegerField()),
            ],
            options={
                'db_table': 'Tools',
            },
        ),
    ]
