# Generated by Django 4.2.13 on 2024-10-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0021_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('ambulance_plate', models.CharField(max_length=15)),
                ('tool_id', models.IntegerField()),
                ('tool_name', models.CharField(max_length=50)),
                ('isPaid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Bill',
            },
        ),
    ]
