# Generated by Django 4.2.13 on 2024-10-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0022_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='username',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
