# Generated by Django 4.2.13 on 2024-10-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0022_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
