# Generated by Django 4.2.13 on 2024-10-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0023_bill_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='ride_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
