# Generated by Django 4.2.13 on 2024-10-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0023_bill_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='tool_name',
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='tools_used',
            field=models.ManyToManyField(to='ABS.tools'),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
