# Generated by Django 4.2.13 on 2024-10-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0024_remove_bill_tool_name_bill_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment_date',
        ),
    ]
