# Generated by Django 4.2.13 on 2024-10-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0025_remove_bill_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='tools_used',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
    ]
