# Generated by Django 4.2.13 on 2024-10-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0026_remove_bill_tools_used_remove_bill_total_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
